### ISSUE TITLE
optimize field mapping

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#17]
**Is your feature request related to a problem? Please describe.**
Field mapping gets exponentially slower with larger datasets.

**Describe the solution you'd like**
Quicker and simpler field mapping logic, without eliminating the current flexibility.

**Describe alternatives you've considered**
- Avoiding the few instances of pandas apply.
- Converting field mapping functions to receive entire pandas series or dataframes instead of individual values.
- Multiprocessing the field mapping of different datasets, since their activities do not interfere with each other.

**Comment by goatsweater** [comment]
As I'm bringing functions into the common package as part of #10, I'm starting to look at this. I think the logic can be broken down a little bit to give some speedups. The current implementation uses a series of nested loops to determine which actions to take on which fields based on when it sees them in the outer loops. I'm not sure about eliminating looping structures entirely, but I do think it may be possible to implement some method chaining logic to replace some aspects of the current logic structure. This would effectively be implementing the use of series or dataframes through the implementation of a set of methods that support broadcasting. Getting the data structures into the right setup to be passed around is where I'm at right now.

**Comment by goatsweater** [comment]
Although it isn't exactly simple due to the support for conversion chains, some of the methods supported against values can be mapped to their pandas built-in equivalents. Just as an example, splitting values and taking a given index can be achieved with the built-in `.str.split()` call. This would automatically broadcast the results across the column as well, avoiding loops that get slower as the data grows.

**Comment by goatsweater** [comment]
As I've been mapping some functions to their pandas string processing equivalents, I've realized it will be easier to change the names of parameters, essentially redefining some of the functions. There are different parameters for pandas functions that don't always map.

This means there will need to be some exercise to update the configuration files, although it shouldn't be that big of a deal since it is only some fields that will be affected.

**Comment by jessestewart1** [comment]
I think this will be much easier for you if I modify the field mapping functions to accept dataframes instead of individual values - one of the main changes I wanted to implement anyways for speedups.

**Comment by goatsweater** [comment]
I have that modification in place already. I've actually broken it down into two categories: one that accepts columns and one that accepts DataFrames. The problem I'm actually running into is that sometimes the pandas commands will accept more options that are currently supplied, and it isn't obvious what the defaults should be or how exactly it should match. Also, sometimes existing functions take more arguments that an equivalent built-in, so then what to do with the extra parameter is in question. It's really just a difference of API.

**Comment by jessestewart1** [comment]
This is pretty much complete. pandas apply is no longer used for field mapping, all functions handle dataframes, and standardization of data types has created a rapid increase in field mapping speed.

**Comment by jessestewart1** [comment]
closed by https://github.com/jessestewart1/nrn-rrn/pull/25 (unable to link due to being in a different repo)
